FORMAT: 1A
HOST: http://localhost:5005

# Api

Api for platform

## Send Message [/api/v1/{channel}/{chat_id}/send_message]
        
### Send Single Message [POST]

+ Parameters
    + chat_id: 1 (required, number) 
    + channel: "telegram" (required, string)
    
+ Request (application/json)

        {
                "text": "str",
                "image": "null",
                "buttons": [],
                "elements": [],
                "attachments": []
            }
        
+ Response 201 (application/json)

        {
            "code": 201,
            "status":"created",
            "reason": [],
        }
        
+ Response 400 (application/json)

        {
            "code": 400, 
            "status": "failed",
            "reason": [],
        }

+ Response 404 (application/json)

        {
            "code": 404, 
            "status": "not found",
            "reason": [],
        }
+ Response 500 (application/json)

        {
            "code": 500, 
            "status": "server error",
            "reason": [],
        }
        
##  Send Mass Message [/api/v1/send_mass_message]

### Send mass message [POST]

+ Request (application/json)

        {    
            "telegram":{
                "chat_ids":[]
                "message": {
                    "text": "str",
                    "image": "null",
                    "buttons": [],
                    "elements": [],
                    "attachments": []
                    }
            },
            
            "viber":{
                "chat_ids":[]
                "message": {
                    "text": "str",
                    "image": "null",
                    "buttons": [],
                    "elements": [],
                    "attachments": []
                    }
            },
                
            "whatsapp":{
                "chat_ids":[]
                "message": {
                    "text": "str",
                    "image": "null",
                    "buttons": [],
                    "elements": [],
                    "attachments": []
                    }
            }
        }
        
+ Response 201 (application/json)

        {
            "code": 201,
            "status":"created",
            "reason": [],
        }
        
+ Response 400 (application/json)

        {
            "code": 400, 
            "status": "failed",
            "reason": [],
        }

+ Response 404 (application/json)

        {
            "code": 404, 
            "status": "not found",
            "reason": [],
        }
+ Response 500 (application/json)

        {
            "code": 500, 
            "status": "server error",
            "reason": [],
        }